// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendaZap.Infrastructure.Persistence;

#nullable disable

namespace VendaZap.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("VendaZap.Domain.Entities.AutoReplyTemplate", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<int>("Priority")
                .HasColumnType("integer")
                .HasColumnName("priority");

            b.Property<string>("Response")
                .IsRequired()
                .HasMaxLength(4096)
                .HasColumnType("character varying(4096)")
                .HasColumnName("response");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<string>("Triggers")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("triggers");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_auto_reply_templates");

            b.HasIndex("TenantId", "IsActive")
                .HasDatabaseName("ix_auto_reply_templates_tenant_id_is_active");

            b.ToTable("auto_reply_templates");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Campaign", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<int[]>("ActiveDays")
                .HasColumnType("integer[]")
                .HasColumnName("active_days");

            b.Property<TimeOnly?>("ActiveFrom")
                .HasColumnType("time without time zone")
                .HasColumnName("active_from");

            b.Property<TimeOnly?>("ActiveTo")
                .HasColumnType("time without time zone")
                .HasColumnName("active_to");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("FiltersJson")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)")
                .HasDefaultValue("{}")
                .HasColumnName("filters_json");

            b.Property<string>("MediaUrl")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("media_url");

            b.Property<string>("MessageTemplate")
                .IsRequired()
                .HasMaxLength(4096)
                .HasColumnType("character varying(4096)")
                .HasColumnName("message_template");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<DateTime?>("ScheduledAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("scheduled_at");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<int>("TotalDelivered")
                .HasColumnType("integer")
                .HasColumnName("total_delivered");

            b.Property<int>("TotalRead")
                .HasColumnType("integer")
                .HasColumnName("total_read");

            b.Property<int>("TotalReplied")
                .HasColumnType("integer")
                .HasColumnName("total_replied");

            b.Property<int>("TotalSent")
                .HasColumnType("integer")
                .HasColumnName("total_sent");

            b.Property<int>("Trigger")
                .HasColumnType("integer")
                .HasColumnName("trigger");

            b.Property<int>("TriggerDelayMinutes")
                .HasColumnType("integer")
                .HasColumnName("trigger_delay_minutes");

            b.Property<int>("Type")
                .HasColumnType("integer")
                .HasColumnName("type");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_campaigns");

            b.HasIndex("TenantId")
                .HasDatabaseName("ix_campaigns_tenant_id");

            b.HasIndex("TenantId", "Status")
                .HasDatabaseName("ix_campaigns_tenant_id_status");

            b.ToTable("campaigns");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Contact", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Address")
                .HasMaxLength(300)
                .HasColumnType("character varying(300)")
                .HasColumnName("address");

            b.Property<string>("City")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("city");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Email")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("email");

            b.Property<bool>("IsBlocked")
                .HasColumnType("boolean")
                .HasColumnName("is_blocked");

            b.Property<DateTime?>("LastInteractionAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("last_interaction_at");

            b.Property<string>("Name")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<string>("Notes")
                .HasColumnType("text")
                .HasColumnName("notes");

            b.Property<string>("PhoneNumber")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("phone_number");

            b.Property<string>("State")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("state");

            b.Property<string>("TagsJson")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)")
                .HasDefaultValue("[]")
                .HasColumnName("tags_json");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<int>("TotalOrders")
                .HasColumnType("integer")
                .HasColumnName("total_orders");

            b.Property<decimal>("TotalSpent")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)")
                .HasColumnName("total_spent");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.Property<string>("ZipCode")
                .HasMaxLength(10)
                .HasColumnType("character varying(10)")
                .HasColumnName("zip_code");

            b.HasKey("Id")
                .HasName("pk_contacts");

            b.HasIndex("TenantId")
                .HasDatabaseName("ix_contacts_tenant_id");

            b.HasIndex("PhoneNumber", "TenantId")
                .IsUnique()
                .HasDatabaseName("ix_contacts_phone_number_tenant_id");

            b.ToTable("contacts");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Conversation", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<Guid?>("ActiveOrderId")
                .HasColumnType("uuid")
                .HasColumnName("active_order_id");

            b.Property<string>("AiThreadId")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("ai_thread_id");

            b.Property<Guid?>("AssignedToUserId")
                .HasColumnType("uuid")
                .HasColumnName("assigned_to_user_id");

            b.Property<string>("CartJson")
                .IsRequired()
                .HasMaxLength(5000)
                .HasColumnType("character varying(5000)")
                .HasDefaultValue("{}")
                .HasColumnName("cart_json");

            b.Property<Guid>("ContactId")
                .HasColumnType("uuid")
                .HasColumnName("contact_id");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<DateTime?>("LastMessageAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("last_message_at");

            b.Property<string>("LastMessagePreview")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("last_message_preview");

            b.Property<int>("Mode")
                .HasColumnType("integer")
                .HasColumnName("mode");

            b.Property<int>("Stage")
                .HasColumnType("integer")
                .HasColumnName("stage");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<int>("UnreadCount")
                .HasColumnType("integer")
                .HasColumnName("unread_count");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.Property<string>("WhatsAppConversationId")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("whats_app_conversation_id");

            b.HasKey("Id")
                .HasName("pk_conversations");

            b.HasIndex("AssignedToUserId")
                .HasDatabaseName("ix_conversations_assigned_to_user_id");

            b.HasIndex("ContactId")
                .HasDatabaseName("ix_conversations_contact_id");

            b.HasIndex("TenantId", "Status")
                .HasDatabaseName("ix_conversations_tenant_id_status");

            b.HasIndex("TenantId", "ContactId", "Status")
                .HasDatabaseName("ix_conversations_tenant_id_contact_id_status");

            b.ToTable("conversations");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Message", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<Guid>("ConversationId")
                .HasColumnType("uuid")
                .HasColumnName("conversation_id");

            b.Property<string>("Content")
                .IsRequired()
                .HasMaxLength(4096)
                .HasColumnType("character varying(4096)")
                .HasColumnName("content");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<DateTime?>("DeliveredAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("delivered_at");

            b.Property<int>("Direction")
                .HasColumnType("integer")
                .HasColumnName("direction");

            b.Property<string>("ErrorMessage")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("error_message");

            b.Property<string>("MediaMimeType")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("media_mime_type");

            b.Property<string>("MediaUrl")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("media_url");

            b.Property<DateTime?>("ReadAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("read_at");

            b.Property<int>("Source")
                .HasColumnType("integer")
                .HasColumnName("source");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<string>("TemplateId")
                .HasColumnType("text")
                .HasColumnName("template_id");

            b.Property<int>("Type")
                .HasColumnType("integer")
                .HasColumnName("type");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.Property<string>("WhatsAppMessageId")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("whats_app_message_id");

            b.HasKey("Id")
                .HasName("pk_messages");

            b.HasIndex("WhatsAppMessageId")
                .HasDatabaseName("ix_messages_whats_app_message_id");

            b.HasIndex("ConversationId", "CreatedAt")
                .HasDatabaseName("ix_messages_conversation_id_created_at");

            b.ToTable("messages");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Order", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime?>("CancelledAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("cancelled_at");

            b.Property<string>("CancellationReason")
                .HasColumnType("text")
                .HasColumnName("cancellation_reason");

            b.Property<Guid>("ContactId")
                .HasColumnType("uuid")
                .HasColumnName("contact_id");

            b.Property<Guid>("ConversationId")
                .HasColumnType("uuid")
                .HasColumnName("conversation_id");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("DeliveryAddress")
                .HasColumnType("text")
                .HasColumnName("delivery_address");

            b.Property<string>("DeliveryCity")
                .HasColumnType("text")
                .HasColumnName("delivery_city");

            b.Property<string>("DeliveryState")
                .HasColumnType("text")
                .HasColumnName("delivery_state");

            b.Property<string>("DeliveryZipCode")
                .HasColumnType("text")
                .HasColumnName("delivery_zip_code");

            b.Property<DateTime?>("DeliveredAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("delivered_at");

            b.Property<string>("Notes")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)")
                .HasColumnName("notes");

            b.Property<string>("OrderNumber")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("order_number");

            b.Property<DateTime?>("PaidAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("paid_at");

            b.Property<string>("PaymentInstructions")
                .HasColumnType("text")
                .HasColumnName("payment_instructions");

            b.Property<string>("PaymentLink")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("payment_link");

            b.Property<int>("PaymentMethod")
                .HasColumnType("integer")
                .HasColumnName("payment_method");

            b.Property<string>("PixKey")
                .HasMaxLength(150)
                .HasColumnType("character varying(150)")
                .HasColumnName("pix_key");

            b.Property<DateTime?>("ShippedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("shipped_at");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<string>("TrackingCode")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("tracking_code");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_orders");

            b.HasIndex("ContactId")
                .HasDatabaseName("ix_orders_contact_id");

            b.HasIndex("ConversationId")
                .HasDatabaseName("ix_orders_conversation_id");

            b.HasIndex("TenantId", "OrderNumber")
                .IsUnique()
                .HasDatabaseName("ix_orders_tenant_id_order_number");

            b.HasIndex("TenantId", "Status")
                .HasDatabaseName("ix_orders_tenant_id_status");

            b.ToTable("orders");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.OrderItem", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<Guid>("OrderId")
                .HasColumnType("uuid")
                .HasColumnName("order_id");

            b.Property<Guid>("ProductId")
                .HasColumnType("uuid")
                .HasColumnName("product_id");

            b.Property<string>("ProductName")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("product_name");

            b.Property<int>("Quantity")
                .HasColumnType("integer")
                .HasColumnName("quantity");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_order_items");

            b.HasIndex("OrderId")
                .HasDatabaseName("ix_order_items_order_id");

            b.HasIndex("ProductId")
                .HasDatabaseName("ix_order_items_product_id");

            b.ToTable("order_items");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Product", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Category")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("category");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)")
                .HasColumnName("description");

            b.Property<string>("ExternalLink")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("external_link");

            b.Property<string>("ImageUrl")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("image_url");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<string>("Sku")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("sku");

            b.Property<int>("SortOrder")
                .HasColumnType("integer")
                .HasColumnName("sort_order");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<int>("StockQuantity")
                .HasColumnType("integer")
                .HasColumnName("stock_quantity");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<bool>("TrackStock")
                .HasColumnType("boolean")
                .HasColumnName("track_stock");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_products");

            b.HasIndex("TenantId")
                .HasDatabaseName("ix_products_tenant_id");

            b.HasIndex("TenantId", "Status")
                .HasDatabaseName("ix_products_tenant_id_status");

            b.ToTable("products");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Tenant", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("AwayMessage")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)")
                .HasColumnName("away_message");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<bool>("IsHumanTakeoverEnabled")
                .HasColumnType("boolean")
                .HasColumnName("is_human_takeover_enabled");

            b.Property<string>("LogoUrl")
                .HasColumnType("text")
                .HasColumnName("logo_url");

            b.Property<int>("MaxConcurrentConversations")
                .HasColumnType("integer")
                .HasColumnName("max_concurrent_conversations");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<string>("OpenAiAssistantId")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("open_ai_assistant_id");

            b.Property<int>("Plan")
                .HasColumnType("integer")
                .HasColumnName("plan");

            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("slug");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<DateTime?>("SubscriptionEndsAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("subscription_ends_at");

            b.Property<DateTime?>("TrialEndsAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("trial_ends_at");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.Property<string>("WelcomeMessage")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)")
                .HasColumnName("welcome_message");

            b.Property<string>("WhatsAppAccessToken")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("whats_app_access_token");

            b.Property<string>("WhatsAppBusinessAccountId")
                .HasColumnType("text")
                .HasColumnName("whats_app_business_account_id");

            b.Property<string>("WhatsAppPhoneNumberId")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("whats_app_phone_number_id");

            b.HasKey("Id")
                .HasName("pk_tenants");

            b.HasIndex("Slug")
                .IsUnique()
                .HasDatabaseName("ix_tenants_slug");

            b.ToTable("tenants");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.User", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("AvatarUrl")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("avatar_url");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("email");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");

            b.Property<DateTime?>("LastLoginAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("last_login_at");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("password_hash");

            b.Property<string>("RefreshToken")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("refresh_token");

            b.Property<DateTime?>("RefreshTokenExpiresAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("refresh_token_expires_at");

            b.Property<int>("Role")
                .HasColumnType("integer")
                .HasColumnName("role");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_users");

            b.HasIndex("TenantId")
                .HasDatabaseName("ix_users_tenant_id");

            b.HasIndex("Email", "TenantId")
                .IsUnique()
                .HasDatabaseName("ix_users_email_tenant_id");

            b.ToTable("users");
        });

        // ── owned entities (Money value objects) ──────────────────────────────

        modelBuilder.Entity("VendaZap.Domain.Entities.Product", b =>
        {
            b.OwnsOne("VendaZap.Domain.ValueObjects.Money", "Price", b1 =>
            {
                b1.Property<Guid>("ProductId")
                    .HasColumnType("uuid");

                b1.Property<decimal>("Amount")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("Price");

                b1.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("Currency");

                b1.WithOwner()
                    .HasForeignKey("ProductId");

                b1.ToTable("products");
            });

            b.Navigation("Price").IsRequired();
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Order", b =>
        {
            b.OwnsOne("VendaZap.Domain.ValueObjects.Money", "Subtotal", b1 =>
            {
                b1.Property<Guid>("OrderId").HasColumnType("uuid");
                b1.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("Subtotal");
                b1.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)").HasColumnName("SubtotalCurrency");
                b1.WithOwner().HasForeignKey("OrderId");
                b1.ToTable("orders");
            });

            b.OwnsOne("VendaZap.Domain.ValueObjects.Money", "ShippingCost", b1 =>
            {
                b1.Property<Guid>("OrderId").HasColumnType("uuid");
                b1.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("ShippingCost");
                b1.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)").HasColumnName("ShippingCurrency");
                b1.WithOwner().HasForeignKey("OrderId");
                b1.ToTable("orders");
            });

            b.OwnsOne("VendaZap.Domain.ValueObjects.Money", "Total", b1 =>
            {
                b1.Property<Guid>("OrderId").HasColumnType("uuid");
                b1.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("Total");
                b1.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)").HasColumnName("TotalCurrency");
                b1.WithOwner().HasForeignKey("OrderId");
                b1.ToTable("orders");
            });

            b.Navigation("Subtotal").IsRequired();
            b.Navigation("ShippingCost").IsRequired();
            b.Navigation("Total").IsRequired();
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.OrderItem", b =>
        {
            b.OwnsOne("VendaZap.Domain.ValueObjects.Money", "UnitPrice", b1 =>
            {
                b1.Property<Guid>("OrderItemId").HasColumnType("uuid");
                b1.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("UnitPrice");
                b1.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)").HasColumnName("UnitPriceCurrency");
                b1.WithOwner().HasForeignKey("OrderItemId");
                b1.ToTable("order_items");
            });

            b.OwnsOne("VendaZap.Domain.ValueObjects.Money", "Total", b1 =>
            {
                b1.Property<Guid>("OrderItemId").HasColumnType("uuid");
                b1.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("Total");
                b1.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)").HasColumnName("TotalCurrency");
                b1.WithOwner().HasForeignKey("OrderItemId");
                b1.ToTable("order_items");
            });

            b.Navigation("UnitPrice").IsRequired();
            b.Navigation("Total").IsRequired();
        });

        // ── relationships ─────────────────────────────────────────────────────

        modelBuilder.Entity("VendaZap.Domain.Entities.Campaign", b =>
        {
            b.HasOne("VendaZap.Domain.Entities.Tenant", "Tenant")
                .WithMany()
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Tenant");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Contact", b =>
        {
            b.HasOne("VendaZap.Domain.Entities.Tenant", "Tenant")
                .WithMany()
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Tenant");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Conversation", b =>
        {
            b.HasOne("VendaZap.Domain.Entities.Contact", "Contact")
                .WithMany("Conversations")
                .HasForeignKey("ContactId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("VendaZap.Domain.Entities.Tenant", "Tenant")
                .WithMany()
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("VendaZap.Domain.Entities.User", "AssignedToUser")
                .WithMany()
                .HasForeignKey("AssignedToUserId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("AssignedToUser");
            b.Navigation("Contact");
            b.Navigation("Tenant");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Message", b =>
        {
            b.HasOne("VendaZap.Domain.Entities.Conversation", "Conversation")
                .WithMany("Messages")
                .HasForeignKey("ConversationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Conversation");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Order", b =>
        {
            b.HasOne("VendaZap.Domain.Entities.Contact", "Contact")
                .WithMany("Orders")
                .HasForeignKey("ContactId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("VendaZap.Domain.Entities.Conversation", "Conversation")
                .WithMany()
                .HasForeignKey("ConversationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("VendaZap.Domain.Entities.Tenant", "Tenant")
                .WithMany()
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Contact");
            b.Navigation("Conversation");
            b.Navigation("Tenant");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.OrderItem", b =>
        {
            b.HasOne("VendaZap.Domain.Entities.Order", "Order")
                .WithMany("Items")
                .HasForeignKey("OrderId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("VendaZap.Domain.Entities.Product", "Product")
                .WithMany("OrderItems")
                .HasForeignKey("ProductId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Order");
            b.Navigation("Product");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Product", b =>
        {
            b.HasOne("VendaZap.Domain.Entities.Tenant", "Tenant")
                .WithMany("Products")
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Tenant");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.User", b =>
        {
            b.HasOne("VendaZap.Domain.Entities.Tenant", "Tenant")
                .WithMany("Users")
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Tenant");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Contact", b =>
        {
            b.Navigation("Conversations");
            b.Navigation("Orders");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Conversation", b =>
        {
            b.Navigation("Messages");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Order", b =>
        {
            b.Navigation("Items");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Product", b =>
        {
            b.Navigation("OrderItems");
        });

        modelBuilder.Entity("VendaZap.Domain.Entities.Tenant", b =>
        {
            b.Navigation("Users");
            b.Navigation("Products");
        });

#pragma warning restore 612, 618
    }
}
